// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mwjroocbqndfdrytkwyj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im13anJvb2NicW5kZmRyeXRrd3lqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkzODI3MTYsImV4cCI6MjA2NDk1ODcxNn0.rHYoMLKkYtXwI2Fklwm_PunrFMlKCkvVbN6OXfaFXOU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);